development: &nps
  emails:
    admin:  admin@hosting.vills.me
    robot:
      email:  no-reply@hosting.vills.me
      name:   Hosting Robot

  domain:   localhost:4567

  administrators:
    admin:
      login:    admin
      password: password



test:
  <<: *nps


production:
  emails:
    admin:  admin@t.vills.me
    robot:
      email:  no-reply@t.vills.me
      name:   Hosting Robot

  domain:   t.vills.me

  administrators:
    admin:
      login:    admin
      password: password
